apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        # Rota principal para seu app
        location / {
            # ATUALIZADO
            proxy_pass http://snake-service:3123;
        }

        # Rota para as m√©tricas do seu app
        location /metrics {
            # ATUALIZADO
            proxy_pass http://snake-service:3123;
        }

        # Rota para o Grafana (permanece a mesma)
        location /grafana/ {
            proxy_pass http://grafana:3000;
            proxy_set_header Host $host;
        }
    }